# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-19 18:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyWeightLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=150, verbose_name='Weight')),
                ('w_units', models.IntegerField(choices=[(1, 'Pounds'), (2, 'Kilograms')], verbose_name='Units')),
                ('date', models.DateField(verbose_name='Date')),
                ('tod', models.IntegerField(choices=[(1, 'Morning'), (2, 'Afternoon')], verbose_name='Time of Day')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bodyweight_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FitnessLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=100, verbose_name='Name')),
                ('ename_str', models.CharField(max_length=100, verbose_name='Str Name')),
                ('date', models.DateField(verbose_name='Date')),
                ('activity', models.IntegerField(choices=[(1, 'Weighted Lifting'), (2, 'Body weight Lifting'), (3, 'Cardiovascular')], verbose_name='Exercise')),
                ('reps', models.IntegerField(verbose_name='Repetitions/Time')),
                ('r_units', models.IntegerField(choices=[(1, 'Seconds'), (2, 'Minutes'), (3, 'Repetitions')], verbose_name='Units')),
                ('sets', models.IntegerField(verbose_name='Sets')),
                ('weight', models.IntegerField(default=0, verbose_name='Weight')),
                ('w_units', models.IntegerField(choices=[(1, 'Pounds'), (2, 'Kilograms')], verbose_name='Units')),
                ('fromworkout', models.BinaryField(verbose_name='In Workout?')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fitness_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('desc', models.CharField(max_length=100, verbose_name='Description')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=100, verbose_name='Str Name')),
                ('workout', models.CharField(max_length=100, verbose_name='Workout')),
                ('activity', models.IntegerField(choices=[(1, 'Weighted Lifting'), (2, 'Body weight Lifting'), (3, 'Cardiovascular')], verbose_name='Exercise')),
                ('reps', models.IntegerField(verbose_name='Repetitions/Time')),
                ('r_units', models.IntegerField(choices=[(1, 'Seconds'), (2, 'Minutes'), (3, 'Repetitions')], verbose_name='Units')),
                ('sets', models.IntegerField(verbose_name='Sets')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_exercises', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('workout', models.CharField(max_length=100, verbose_name='Workout')),
                ('weights', models.CharField(max_length=200, verbose_name='Weights')),
                ('w_units', models.IntegerField(choices=[(1, 'Pounds'), (2, 'Kilograms')], verbose_name='Units')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_exercise_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
