# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-19 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100, verbose_name='Username')),
                ('ename', models.CharField(max_length=100, verbose_name='Name')),
                ('date', models.DateField(verbose_name='Date')),
                ('activity', models.IntegerField(choices=[(1, 'Weighted Lifting'), (2, 'Body weight Lifting'), (3, 'Cardiovascular')], verbose_name='Exercise')),
                ('reps', models.IntegerField(verbose_name='Repetitions/Time')),
                ('weight', models.IntegerField(default=0, verbose_name='Weight')),
                ('units', models.IntegerField(choices=[(1, 'Pounds'), (2, 'Kilograms')], verbose_name='Units')),
            ],
        ),
    ]
