# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-19 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyFitness', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnesslog',
            name='fromworkout',
            field=models.BooleanField(default=False, verbose_name='In Workout?'),
        ),
    ]
