# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-19 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyFitness', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fitnesslog',
            old_name='units',
            new_name='w_units',
        ),
        migrations.AddField(
            model_name='fitnesslog',
            name='r_units',
            field=models.IntegerField(choices=[(1, 'Seconds'), (2, 'Minutes'), (3, 'Repetitions')], default=1, verbose_name='Units'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fitnesslog',
            name='sets',
            field=models.IntegerField(default=1, verbose_name='Sets'),
            preserve_default=False,
        ),
    ]
