# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-19 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyFitness', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='FitnessLog',
            name='ename',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
