# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-19 05:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('MyFitness', '0002_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessLog',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('ename', models.CharField(max_length=200, verbose_name='Name')),
                ('date', models.DateField(verbose_name='Date')),
                ('activity', models.IntegerField(choices=[(1, 'Weighted Lifting'), (2, 'Body weight Lifting'), (3, 'Cardiovascular')], verbose_name='Exercise')),
                ('reps', models.IntegerField(verbose_name='Repetitions/Time')),
                ('weight', models.IntegerField(default=0, verbose_name='Weight')),
                ('units', models.IntegerField(choices=[(1, 'Pounds'), (2, 'Kilograms')], verbose_name='Units')),
            ],
        ),
    ]
