# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-19 03:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MyFitness', '0002_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessLog',
            fields=[
                ('ename', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('activity', models.IntegerField(choices=[(1, 'Weighted Lifting'), (2, 'Body weight Lifting'), (3, 'Cardiovascular')], verbose_name='Exercise')),
                ('reps', models.IntegerField(max_length=200, verbose_name='Repetitions/Time')),
                ('units', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
