# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-19 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyFitness', '0002_auto_20170619_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitnesslog',
            name='fromworkout',
        ),
        migrations.AddField(
            model_name='fitnesslog',
            name='workout',
            field=models.CharField(default='None', max_length=200, verbose_name='Workout'),
            preserve_default=False,
        ),
    ]
