# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-19 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyFitness', '0002_auto_20160519_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitnesslog',
            name='id',
        ),
        migrations.RemoveField(
            model_name='fitnesslog',
            name='user',
        ),
        migrations.AlterField(
            model_name='fitnesslog',
            name='ename',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Name'),
        ),
    ]
