# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-13 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyFitness', '0002_auto_20160519_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyWeightLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100, verbose_name='Username')),
                ('weight', models.FloatField(default=150, verbose_name='Weight')),
                ('w_units', models.IntegerField(choices=[(1, 'Pounds'), (2, 'Kilograms')], verbose_name='Units')),
                ('tod', models.IntegerField(choices=[(1, 'Morning'), (2, 'Afternoon')], verbose_name='Time of Day')),
            ],
        ),
    ]
