# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-19 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyFitness', '0003_auto_20170619_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='count',
            field=models.IntegerField(default=3, verbose_name='Number of Exercises'),
            preserve_default=False,
        ),
    ]
