# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-13 02:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('MyFitness', '0003_bodyweightlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodyweightlog',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 1, 13, 2, 41, 17, 923000, tzinfo=utc), verbose_name='Date'),
            preserve_default=False,
        ),
    ]
