# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-19 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyFitness', '0003_auto_20160519_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnesslog',
            name='user',
            field=models.CharField(default=1, max_length=100, primary_key=True, serialize=False, verbose_name='Username'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fitnesslog',
            name='ename',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
