# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-19 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyFitness', '0004_auto_20160519_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnesslog',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fitnesslog',
            name='user',
            field=models.CharField(max_length=100, verbose_name='Username'),
        ),
    ]
