# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-16 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyFitness', '0004_bodyweightlog_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutDay',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100, verbose_name='Username')),
                ('days', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], verbose_name='Days')),
            ],
        ),
    ]
