# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-20 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyFitness', '0004_workout_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='color',
            field=models.CharField(default='4277f4', max_length=6, verbose_name='Color'),
            preserve_default=False,
        ),
    ]
