# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-20 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyFitness', '0005_workout_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnesslog',
            name='workout',
            field=models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='MyFitness.Workout'),
        ),
    ]
