# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-19 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyFitness', '0005_auto_20160518_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnesslog',
            name='units',
            field=models.IntegerField(choices=[(1, 'Pounds'), (2, 'Kilograms')], verbose_name='Units'),
        ),
        migrations.AlterField(
            model_name='fitnesslog',
            name='weight',
            field=models.IntegerField(verbose_name='Weight'),
        ),
    ]
