# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-16 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyFitness', '0006_auto_20170116_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutday',
            name='days',
            field=models.CommaSeparatedIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], max_length=100, verbose_name='Days'),
        ),
    ]
