# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-20 17:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyFitness', '0006_auto_20170620_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnesslog',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout', to='MyFitness.Workout'),
        ),
    ]
