# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-20 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyFitness', '0007_auto_20170620_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutexercise',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exer_workout', to='MyFitness.Workout'),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_workout', to='MyFitness.Workout'),
        ),
    ]
