# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-16 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyFitness', '0008_auto_20170116_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutday',
            name='days',
            field=models.CharField(choices=[('Mo', 'Monday'), ('Tu', 'Tuesday'), ('We', 'Wednesday'), ('Th', 'Thursday'), ('Fr', 'Friday'), ('Sa', 'Saturday'), ('Su', 'Sunday')], max_length=100, verbose_name='Days'),
        ),
    ]
