# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-20 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyFitness', '0008_auto_20170620_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutexercise',
            name='workout',
            field=models.CharField(max_length=100, verbose_name='Workout'),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='workout',
            field=models.CharField(max_length=100, verbose_name='Workout'),
        ),
    ]
