# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-16 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyFitness', '0009_auto_20170116_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutday',
            name='days',
        ),
        migrations.AddField(
            model_name='workoutday',
            name='day',
            field=models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], default=1, verbose_name='Day'),
            preserve_default=False,
        ),
    ]
