# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-22 05:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyFitness', '0009_auto_20170620_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnesslog',
            name='wlog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='workout_log', to='MyFitness.WorkoutLog'),
            preserve_default=False,
        ),
    ]
