# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-22 05:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyFitness', '0010_fitnesslog_wlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitnesslog',
            name='workout',
        ),
    ]
