# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-22 05:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyFitness', '0011_remove_fitnesslog_workout'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnesslog',
            name='workout',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='workout', to='MyFitness.Workout'),
            preserve_default=False,
        ),
    ]
